[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "apice"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.4.2",
    "matplotlib>=3.10.3",
    "mne>=1.9.0",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "numexpr>=2.10.2",
    "prettytable>=3.16.0",
    "progressbar33>=2.4",
    "scipy>=1.16.0",
    "tabulate>=0.9.0",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
apice = ["default_cfg/*.json"]
